### ISSUE TITLE
The custom plugin no longer looks at the custom-strider.json file

### ISSUE THREAD

**Issue by morkeleb** [Strider-CD/strider-custom#10]
I just created a new project and chose custom (head for version 1.4.0). It creates the project, I can load the custom plugin which I had to add manually.
Then run the project, and it just fetches the code from github. It doesn't run the steps specified in my custom-strider.json file.

**Comment by knownasilya** [comment]
Is the custom-strider.json file even honored anymore? I don't see it in the code. Unless you are referring to `strider.json`.

**Comment by knownasilya** [comment]
`strider.json` does override this plugin.
