### ISSUE TITLE
Issue with command pipes

### ISSUE THREAD

**Issue by glena** [Strider-CD/strider-custom#22]
Hi,

One of our projects is using Strider to deploy a WordPress plugin using SVN.

One of the commands, adds to svn all the new files doing the following
`svn status | grep '\?' | awk '{print $2}'| xargs svn add`

with the following output
```
+ awk '{print $2}'
+ svn status
+ xargs svn add
+ grep '\?'
```

For some reason, this stop working and after check the logs, the output change like the pipes where executing  in the other way
```
+ xargs svn add
+ awk '{print $2}'
+ grep '\?'
+ svn status
```

adn after update the command to
`xargs svn add | awk '{print $2}' | grep '\?' | svn status`

it is working again. 

Is there any reason for this awkward issue?

**Comment by knownasilya** [comment]
No idea... Maybe something to do with the arguments passed here: https://github.com/Strider-CD/strider-custom/blob/master/worker.js#L34

**Comment by glena** [comment]
weird. I solved this (I found another way to do this) but it is really weird. Thanks
