### ISSUE TITLE
The shell editor view doesn't initialize correctly

### ISSUE THREAD

**Issue by vqoph** [Strider-CD/strider-custom#28]
![capture d ecran 2016-01-28 a 22 40 32](https://cloud.githubusercontent.com/assets/5341141/12659645/2d833264-c610-11e5-915a-b5562f2d1edd.png)

has you can see in the screenshot, the editor doesn't initialize correctly, does anyone have the same issue ?

to initialize this view i need to resize my browser window

**Comment by knownasilya** [comment]
I see the same issue. It fixes if you open devtools. I've yet to find the cause.

**Comment by vqoph** [comment]
I can try to help but do you have any recommandation to contribute ?

**Comment by knownasilya** [comment]
Well the codeblocks use https://github.com/angular-ui/ui-codemirror so maybe some dependency issues?

**Comment by vqoph** [comment]
I've looked at angular-ui/ui-codemirror issues and the angular-ui/ui-codemirror#111 seems to be the same problem as our, i'll try their workaround

**Comment by vqoph** [comment]
where do the project manage front end dependencies ?  (it's the first time i contribute to a strider-cd plugin project)

**Comment by knownasilya** [comment]
The frontend deps for this plugin are actually in strider itself (I think this is one of the older plugins).

P.S. maybe we can set `ui-refresh` to something better, like the current date..

**Comment by knownasilya** [comment]
https://github.com/Strider-CD/strider/tree/master/vendor/CodeMirror

**Comment by vqoph** [comment]
in strider project codemirror is set to 3.18.0 and latest is 5.11.1 may be an update of the library can solve our problem

**Comment by knownasilya** [comment]
No, we would have to update angular as well, and it's a big project. But i think I know why it's not working :+1:  Will try to fix in the next day or two.

**Comment by vqoph** [comment]
ok i understand ,
i tryed to set `ui-refresh` to a time based value but i haven't found the right controller

**Comment by knownasilya** [comment]
The issue is that the scope changes, so it breaks the setup.. trying to figure out the scope issue..

**Comment by knownasilya** [comment]
Should be fixed in master.

**Comment by vqoph** [comment]
Well it's working for me ! ;) 
thx a lot for your time
